# @package _global_

algorithm:
  _target_: memorax.algorithms.PQNConfig
  name: pqn
  num_envs: 32
  num_eval_envs: 16
  num_steps: 128
  gamma: 0.95
  td_lambda: 0.95
  num_minibatches: 4
  update_epochs: 4

