# @package _global_

algorithm:
  _target_: memorax.algorithms.R2D2Config
  name: r2d2
  num_envs: 128
  num_eval_envs: 0
  buffer_size: 1_000_000
  gamma: 0.99
  tau: 0.005
  target_network_frequency: 1
  batch_size: 128
  start_e: 1.0
  end_e: 0.01
  exploration_fraction: 0.25
  learning_starts: 5000
  train_frequency: 4
  burn_in_length: 32
  sequence_length: 128
