total_timesteps: 500_000
num_train_steps: 100_000
num_evaluation_steps: 10_000
seed: 0
num_seeds: 1

defaults:
  - _self_
  - algorithm: dqn
  - environment: cartpole
  - logger: []
  - optional hyperparameter: ${algorithm}/${environment}

logger:
  _target_: memory_rl.loggers.Logger
  _convert_: all
  loggers:

