total_timesteps: 5_000_000
num_train_steps: 100_000
num_evaluation_steps: 10_000
seed: 0

defaults:
  - _self_
  - algorithm: dqn
  - environment: cartpole
  - logger: default
  - optional hyperparameter: ${algorithm}/${environment}

hydra:
  output_subdir: null
