total_timesteps: 1_000_000
num_train_steps: 50_000
evaluate_every: 100_000
seed: 0
num_seeds: 1

defaults:
  - _self_
  - algorithm: dqn
  - environment: cartpole
  - logger: []
  - optional hyperparameter: ${algorithm}/${environment}

logger:
  _target_: memory_rl.loggers.Logger
  _convert_: all
  loggers:

